### ISSUE TITLE
renaming a resource does not work

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-reva#14]
trying to rename a file  results in an empty reply
```
curl 'http://localhost:9140/remote.php/webdav/home/welcome.txt' -X MOVE -u user0:123456 -H 'Destination: http://localhost:9140/remote.php/webdav/home/welcome2.txt' 
curl: (52) Empty reply from server
```

```
1:13PM INF home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/owncloud/ocdav/move.go:39 > move dst=http://localhost:9140/remote.php/webdav/home/welcome2.txt overwrite= pid=6325 pkg=rhttp src=/home/welcome.txt traceid=93fa45c24cd755393dac52fe88f46f82
2020-01-21 13:13:08.180761 I | http: panic serving 127.0.0.1:54654: interface conversion: interface {} is nil, not string
goroutine 42 [running]:
net/http.(*conn).serve.func1(0xc0007666e0)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x20be9e0, 0xc0016244e0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*svc).doMove(0xc00000ff00, 0x7fb5003c3390, 0xc0007623c0, 0xc00010f400, 0xc0011070a8, 0x1)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/owncloud/ocdav/move.go:71 +0x1b61
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*WebDavHandler).Handler.func1(0x7fb5003c3390, 0xc0007623c0, 0xc00010f400)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/owncloud/ocdav/webdav.go:57 +0x1ec
net/http.HandlerFunc.ServeHTTP(0xc0002d7420, 0x7fb5003c3390, 0xc0007623c0, 0xc00010f400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*svc).Handler.func1(0x7fb5003c3390, 0xc0007623c0, 0xc00010ec00)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/owncloud/ocdav/ocdav.go:148 +0x629
net/http.HandlerFunc.ServeHTTP(0xc0015ea290, 0x7fb5003c3390, 0xc0007623c0, 0xc00010ec00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fb5003c3390, 0xc0007623c0, 0xc00010e400)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:300 +0x185
net/http.HandlerFunc.ServeHTTP(0xc0002a1560, 0x7fb5003c3390, 0xc0007623c0, 0xc00010e400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.(*Server).getHandler.func1(0x7fb5003c3390, 0xc0007623c0, 0xc00010e400)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:247 +0x46b
net/http.HandlerFunc.ServeHTTP(0xc0015eaaf0, 0x7fb5003c3390, 0xc0007623c0, 0xc00010e400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fb5003c3390, 0xc0007623c0, 0xc00010e300)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:300 +0x185
net/http.HandlerFunc.ServeHTTP(0xc0002a17a0, 0x7fb5003c3390, 0xc0007623c0, 0xc00010e300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rs/cors.(*Cors).Handler.func1(0x7fb5003c3390, 0xc0007623c0, 0xc00010e300)
	/home/artur/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b8
net/http.HandlerFunc.ServeHTTP(0xc0000c2840, 0x7fb5003c3390, 0xc0007623c0, 0xc00010e300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fb5003c3390, 0xc0007623c0, 0xc00010e100)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:300 +0x185
net/http.HandlerFunc.ServeHTTP(0xc0002a1aa0, 0x7fb5003c3390, 0xc0007623c0, 0xc00010e100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/auth.New.func1.1(0x7fb5003c3390, 0xc0007623c0, 0xc000221300)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/interceptors/auth/auth.go:230 +0xdb9
net/http.HandlerFunc.ServeHTTP(0xc0006e8bd0, 0x7fb5003c3390, 0xc0007623c0, 0xc000221300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fb5003c3390, 0xc0007623c0, 0xc000221200)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:300 +0x185
net/http.HandlerFunc.ServeHTTP(0xc0002a1ad0, 0x7fb5003c3390, 0xc0007623c0, 0xc000221200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/log.loggingHandler.ServeHTTP(0x2a2d7c0, 0xc0002a1ad0, 0x2a65d60, 0xc000550230, 0xc000221200)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/interceptors/log/log.go:57 +0x297
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x2a65d60, 0xc000550230, 0xc000221100)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:300 +0x185
net/http.HandlerFunc.ServeHTTP(0xc0002a1b30, 0x2a65d60, 0xc000550230, 0xc000221100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/appctx.handler.func1(0x2a65d60, 0xc000550230, 0xc000221000)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/interceptors/appctx/appctx.go:52 +0x5e5
net/http.HandlerFunc.ServeHTTP(0xc00011a4d0, 0x2a65d60, 0xc000550230, 0xc000221000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc0000e9270, 0x2a65d60, 0xc000550230, 0xc000220e00)
	/home/artur/go/pkg/mod/go.opencensus.io@v0.22.2/plugin/ochttp/server.go:92 +0x2b9
net/http.serverHandler.ServeHTTP(0xc0001182a0, 0x2a644e0, 0xc000118380, 0xc000220e00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0007666e0, 0x2a6c8e0, 0xc00008a540)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e

**Comment by dpakach** [comment]
Also trashbin restore doesn't works. Since it is a similar MOVE request I think it's the same issue.

**Comment by dpakach** [comment]
This issue seems to be resolved but works when running through phoenix but the dav endpoints seems to have another error in itself.
Raised at https://github.com/owncloud/ocis-reva/issues/119
Can we close this @butonic  @IljaN

**Comment by PVince81** [comment]
```
make test-acceptance-api \
TEST_SERVER_URL=http://localhost:9140 \
TEST_EXTERNAL_USER_BACKENDS=true \
TEST_OCIS=true \
OCIS_REVA_DATA_ROOT=/var/tmp/reva/ \
BEHAT_FILTER_TAGS='~@skipOnOcV10&&~@skipOnLDAP&&@TestAlsoOnExternalUserBackend&&~@local_storage&&@issue-ocis-reva-14'
```

still a lot of failed scenarios:
```
/srv/www/htdocs/owncloud/tests/acceptance/features/apiMain/checksums.feature:113
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiMain/checksums.feature:114
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiAuthWebDav/webDavMOVEAuth.feature:33
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:12
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:25
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:34
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:61
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:62
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:64
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:79
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagementBasic/createShare.feature:422
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagementBasic/createShare.feature:423
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagementBasic/createShare.feature:454
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagementBasic/createShare.feature:455
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:20
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:21
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:36
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:37
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:54
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:55
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:57
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:70
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:83
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:26
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:27
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:28
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:29
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:30
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:32
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:45
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:58
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:72
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:87
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:106
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:124
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:134
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:140
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:155
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:172
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:173
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:183
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:184
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:203
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:204
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:213
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:214
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:223
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:224
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:233
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:234
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:239
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileToBlacklistedNameAsync.feature:12
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileToBlacklistedNameAsync.feature:18
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileToBlacklistedNameAsync.feature:26
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileToExcludedDirectoryAsync.feature:12
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileToExcludedDirectoryAsync.feature:19
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileToExcludedDirectoryAsync.feature:27
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolder.feature:20
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolder.feature:21
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolder.feature:32
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolder.feature:33
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolder.feature:44
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolder.feature:45
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature:20
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature:21
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature:33
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature:34
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature:67
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature:68
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature:21
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature:22
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature:34
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature:35
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature:70
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature:71
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:21
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:22
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:34
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:35
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:45
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:46
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:57
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:58
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:68
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:69
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:89
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:90
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:91
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:92
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:112
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:113
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:136
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:137
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:138
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:139
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:160
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:161
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:181
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:182
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:200
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:201
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:209
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:210
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:218
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:219
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:254
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:255
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:270
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:271
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:279
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:280
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:281
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature:17
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature:18
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature:27
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature:28
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature:60
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature:61
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature:18
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature:19
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature:28
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature:29
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature:63
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature:64
```

a bunch of those are related to other still unimplemented parts (like checksum, group management, etc)

so those test tags will need to be replaced with different ones

**Comment by individual-it** [comment]
The tests fail because there is no skeleton folder, I've created an issue https://github.com/owncloud/ocis-reva/issues/167

**Comment by PVince81** [comment]
when renaming in the web UI I noticed that I'm also receiving an error, even though the rename worked. so there's more to it.

**Comment by individual-it** [comment]
hope that we will know more details when https://github.com/owncloud/ocis-reva/issues/167 is implemented

**Comment by PVince81** [comment]
renaming was broken already in OCIS, fixed by https://github.com/cs3org/reva/pull/729

**Comment by PVince81** [comment]
updated list, likely the same as before:
```
/srv/www/htdocs/owncloud/tests/acceptance/features/apiMain/checksums.feature:113
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiMain/checksums.feature:114
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiAuthWebDav/webDavMOVEAuth.feature:35
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:12
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:25
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:34
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:61
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:62
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:64
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagement/moveReceivedShare.feature:79
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagementBasic/createShare.feature:380
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagementBasic/createShare.feature:381
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagementBasic/createShare.feature:412
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareManagementBasic/createShare.feature:413
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:20
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:21
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:36
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:37
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:54
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:55
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:57
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:70
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiShareOperations/changingFilesShare.feature:83
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:26
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:27
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:28
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:29
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:30
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:32
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:45
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:58
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:72
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:87
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:106
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:124
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:134
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:140
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:155
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:172
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:173
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:183
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:184
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:203
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:204
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:213
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:214
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:223
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:224
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:233
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:234
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature:239
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileToBlacklistedNameAsync.feature:12
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileToBlacklistedNameAsync.feature:18
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileToBlacklistedNameAsync.feature:26
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileToExcludedDirectoryAsync.feature:12
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileToExcludedDirectoryAsync.feature:19
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFileToExcludedDirectoryAsync.feature:27
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolder.feature:20
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolder.feature:21
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolder.feature:32
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolder.feature:33
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolder.feature:44
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolder.feature:45
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature:20
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature:21
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature:33
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature:34
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature:67
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature:68
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature:21
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature:22
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature:34
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature:35
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature:70
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature:71
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:21
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:22
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:34
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:35
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:45
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:46
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:57
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:58
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:68
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:69
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:89
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:90
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:91
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:92
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:112
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:113
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:136
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:137
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:138
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:139
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:160
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:161
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:181
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:182
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:200
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:201
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:209
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:210
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:218
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:219
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:254
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:255
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:270
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:271
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:279
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:280
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFile.feature:281
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature:17
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature:18
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature:27
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature:28
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature:60
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature:61
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature:18
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature:19
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature:28
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature:29
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature:63
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature:64
```

**Comment by PVince81** [comment]
let's rewrite the tests, at least the ones that only need a small number of files

**Comment by PVince81** [comment]
never mind, skeleton files will arrive https://github.com/owncloud/ocis-reva/issues/167

**Comment by individual-it** [comment]
Skeleton folder emulation is in the API tests, so now we need to enable tests and see which one do work and which one still fail.
Some tests might have to be rewritten e.g. if the check at the end only downloads part of the file as that does not work with ocis ether. But that should not stop us from running the rename/move tests

**Comment by PVince81** [comment]
ok, I'll leave this up to the QA team for now, please assign accordingly once someone starts working on processing these tests
if some tests are genuinely broken due to OCIS issues, please raise separate tickets and let me know

**Comment by HariBhandari07** [comment]
Some of the file/folder renaming operations fails in ocis due to the bug mentioned in this issue https://github.com/owncloud/ocis-reva/issues/211

**Comment by individual-it** [comment]
@HariBhandari07 please create scenarios that demonstrate the current behaviour and skip them on oc10
